src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @Vich\Uploadable()
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="article", cascade={"persist"})
     */
    private $images;

    
    /**
     * @Assert\All({
     *   @Assert\Image(
     *     mimeTypes={"image/jpeg", "image/png", "image/gif"},
     *     mimeTypesMessage = "Please upload a valid Image",
     *     maxSize="50M"
     * 
     
     *
     * )
     * })
     * 
     */
    private $imageFiles;



    /**
     * Article constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->date = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }

     /**
     * @return mixed
     */
    public function getImageFiles()
    {
        return $this->imageFiles;
    }
    public function setImageFiles($imageFiles): self
    {
        foreach($imageFiles as $imageFile) {
            $image = new Image();
            $image->setImageFile($imageFile);
            $this->addImage($image);
        }
        $this->imageFiles = $imageFiles;
        return $this;
    }

}

src/Entity/Files.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * @ORM\Entity(repositoryClass="App\Repository\FilesRepository")
 */
class Files
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage = "Please upload a valid PDF"
     * )
     */
    private $url;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CategoryFiles", inversedBy="files")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="files")
     */
    private $user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrl()
    {
        return $this->url;
    }

    public function setUrl(UploadedFile $file=null)
    {
        $this->url = $file;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?CategoryFiles
    {
        return $this->category;
    }

    public function setCategory(?CategoryFiles $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function upload()
    {
        if(null===$this->url)
        {
            return;
        }
        $name=  $this->url->getClientOriginalName();
        $this->url->move($this->getUploadDir(),$name);
        $this->url=$name;
    }

    public function getUploadDir()
    {
        return 'uploads/documents';
    }


    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getUrl();
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Form\Article1Type;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ArticleRepository;
use App\Entity\Article;
use App\Entity\Image;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{

    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function article()
    {
        
        $article=$this->getDoctrine()
        ->getRepository('App:Article')
        ->findByArticle()
    ;
        return $this->render('article/index.html.twig', [
            'articles' => $article,
        ]);
    }

    /**
     * @Route("/new", name="article_new")
     * @param Request $request
     * @return Response
     * @throws \Exception
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(Article1Type::class, $article);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();
            return $this->redirectToRoute('article_index');
        }
      
        return $this->render('article/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

        /**
     * @Route("/{id}", name="article_show", methods={"GET"})
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     *@IsGranted({"ROLE_ADMIN"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(Article1Type::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $date = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('article_index', [
                'id' => $article->getId(),
            ]);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="article_delete")
     * @param ArticleRepository $articleRepository
     * @param int $id
     * @return RedirectResponse
     * @IsGranted({"ROLE_ADMIN"})
     */
    public function delete(ArticleRepository $articleRepository, int $id): RedirectResponse
    {
        $article = $articleRepository->find($id);
        $em = $this->getDoctrine()->getManager();
        foreach ($article->getImages() as $image) {
            $article->removeImage($image);
        }
        $em->remove($article);
        $em->flush();
        return $this->redirectToRoute('article_index');
    }

}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn" style="color: white;">Supprimer l'article</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

<div>
<button class="btn">{{ button_label|default('Update') }}</button>
</div>
{{ form_end(form) }}

templates/article/all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <link rel="stylesheet" href="{{asset('/css/bootstrap.min.css')}}" type="text/css"/>

    <div class="blocTitre">
        <div class="titrepage">Les Actualités</div>
        <div class="sous-titrepage"><a href="{{ path('admin_index') }}">Retour à l'espace admin</a>
        </div>
    </div>
    <div id="articles_pages">
        <table class="table">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Content</th>
                <th>date</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for article in articles %}
                <tr>
                    <td>{{ article.titre }}</td>
                    <td>{{ article.content}}</td>
                    <td>{{ article.date|date('d/m/Y H:i')}}</td>
                    <td><a class='btn btn-xs' style="background-color: black;color: white;" href="{{ path('article_show', {'id': article.id}) }}">Voir</a></td>
                    <td><a class='btn btn-xs' style="background-color: black;color: white;" href="{{ path('article_edit', {'id': article.id}) }}">Editer</a></td>
                    <td>{{ include('article/_delete_form.html.twig') }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('article_new') }}">Ajouter un article</a>
    </div>
{% endblock %}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Files{% endblock %}

{% block body %}

       <div class="blocTitre">
        <div class="titrepage">Editer un article</div>
           <div class="sous-titrepage"><a href="{{ path('admin_article_index') }}">Page précédente</a>
           </div>
           <br>
           <br>
    {{ include('article/_form.html.twig')}}
           {% for image in article.images %}
                            <a data-fancybox="images" href="{{ asset(image.webPath) }}" data-caption="{{image.alt }}">
                                <img tabindex="{{article.id}}" class="img-fluid img-thumbnail" width="24%" src="{{ asset(image.webPath) }}" alt="{{image.alt }}"/>
                            </a>
                   <a class="btn btn-danger btn-xs" title="supprimer l'image" href="{{ path('admin_delete_image', {'id': image.id}) }}" data-turbolinks="false">supprimer</a>
        {% endfor %}
    {{ include('article/_delete_form.html.twig') }}

        <div>
    <br>
    </div>
{% endblock %}

templates/article/index.html.twig
{% extends "base.html.twig" %}    
{% block title %}L'actualité{% endblock %}
{% block body %}

    <div class="blocTitre">
        <div class="titrepage">L'actualité du chantier</div>
        <div class="sous-titrepage">Cette page a pour objectif de vous tenir informé de l'avancement des travaux.</div>
    </div>
    <div class="ArticleMain">
        {% for article in articles %}
            <div class="article">
                <div class="titre">
                    {{ article.titre }}
                </div>
                  {% if is_granted('ROLE_ADMIN')%}
                  <div>
                    <a class="add" href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
                    <a class="add" href="{{ path('article_new') }}"><span >Ajouter un article</span></a>
                    </div>
                 {% endif %}
                <div class="texteArticle">
                    {{article.content|nl2br}}
                </div>
                <div class="bloc-enimages">
                    <div class="imagegalerie">
                        {% for image in article.images %}
                            {% if 'youtube' in image.url %}
                            {% elseif 'pdf' in image.url %}
                                <a href="{{ asset(image.webPath) }}"> {{ image.alt }}</a>
                            {% else %}
                                <div class="photo">
                                    <a data-fancybox="images" href="{{ asset(image.webPath) }}" data-caption="{{image.alt }}">
                                        <img tabindex="{{article.id}}" class="photoarticle" src="{{ asset(image.webPath) }}" alt="{{image.alt }}"/>
                                    </a>
                                 </div>
                            {% endif %}
                        {%endfor%}
                  
                    </div>
                </div>
                {% for image in article.images %}
                    {% if 'youtube' in image.url %}
                        <iframe src="{{image.url}}" frameborder="0" allowfullscreen style=""></iframe>
                    {% else %}
                    {% endif %}
                {%endfor%}
            </div>
        {% else %}
            <li>BDD vide</li>
        {% endfor %}
    </div>
    </body>
    
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
       <div class="blocTitre">
        <div class="titrepage">Créer un article</div>
           <div class="sous-titrepage"><a href="{{ path('article_index') }}">Page précédente</a>

           </div>
<br>
           <br>
    {{ include('article/_form.html.twig') }}

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <link rel="stylesheet" href="{{asset('/css/bootstrap.min.css')}}" type="text/css"/>

    <div class="blocTitre">
        <div class="titrepage">Article</div>
        <div class="sous-titrepage"><a href="{{ path('article_index') }}">Page précédente</a>
        </div>
    </div>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <a href="{{ path('article_edit', {'id': article.id}) }}">Editer l'article</a>
            <table class="table">
                <tbody>
                <tr>
                    <th>Titre</th>
                    <td>{{ article.titre }}</td>
                </tr>
                <tr>
                    <th>Content</th>
                    <td>{{ article.content }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ article.date ? article.date|date('Y-m-d H:i:s') : '' }}</td>
                </tr>

                <tr>
                    <th>images</th>
                    <td>{% for image in article.images %}
                            <a data-fancybox="images" href="{{ asset(image.webPath) }}" data-caption="{{image.alt }}">
                                <img tabindex="{{article.id}}" src="{{ asset(image.webPath) }}" alt="{{image.alt }}"/>
                            </a>
                        {%endfor%}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    {{ include('article/_delete_form.html.twig') }}
{% endblock %}